"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useState } from "react";
import { AppShell } from "../components/app-shell";
import { Icon } from "../components/icons";
import { PageIntro } from "../components/product-ui";

type AutoApplySettings = { enabled: boolean; minimumMatch: number; dailyLimit: number; jobType: string };
const defaults: AutoApplySettings = { enabled: false, minimumMatch: 75, dailyLimit: 5, jobType: "Full-time" };

export default function AutoApplyPage() {
  const [settings, setSettings] = useState<AutoApplySettings>(defaults);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    try { setSettings({ ...defaults, ...JSON.parse(window.localStorage.getItem("jobbot.auto-apply") ?? "{}") }); } catch { /* Keep defaults. */ }
  }, []);

  function update(next: Partial<AutoApplySettings>) { setSaved(false); setSettings((current) => ({ ...current, ...next })); }
  function saveSettings() { window.localStorage.setItem("jobbot.auto-apply", JSON.stringify(settings)); setSaved(true); }

  return <AppShell><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:px-10"><PageIntro eyebrow="Automation with a human in control" title="Set your application guardrails." description="Decide exactly what JobBot can prepare for you. Any CAPTCHA, verification, or sensitive question stays with you." />
    <div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--card-shadow)] sm:p-6"><div className="flex flex-col gap-5 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Auto-apply queue</h2><p className="mt-1 text-sm leading-6 text-[var(--text-muted)]">Prepare matching jobs for review based on your rules.</p></div><button type="button" onClick={() => update({ enabled: !settings.enabled })} className={`relative h-8 w-14 rounded-full transition ${settings.enabled ? "bg-emerald-500" : "bg-slate-400/40"}`} aria-pressed={settings.enabled} aria-label="Toggle auto apply"><span className={`absolute top-1 h-6 w-6 rounded-full bg-white shadow transition ${settings.enabled ? "left-7" : "left-1"}`} /></button></div>
      <div className={`mt-6 space-y-6 transition ${settings.enabled ? "" : "opacity-65"}`}><label className="block"><span className="flex justify-between text-sm font-semibold"><span>Minimum match score</span><span className="text-[var(--brand)]">{settings.minimumMatch}%</span></span><input type="range" min="50" max="95" step="5" value={settings.minimumMatch} onChange={(event) => update({ minimumMatch: Number(event.target.value) })} className="mt-3 w-full accent-cyan-500" /><span className="mt-1 flex justify-between text-xs text-[var(--text-faint)]"><span>50% broad</span><span>95% selective</span></span></label><div className="grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-semibold">Daily application limit</span><select value={settings.dailyLimit} onChange={(event) => update({ dailyLimit: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] px-3 py-3 text-sm outline-none focus:border-[var(--brand)]">{[3, 5, 10, 15].map((limit) => <option key={limit} value={limit}>{limit} applications</option>)}</select></label><label><span className="text-sm font-semibold">Job type</span><select value={settings.jobType} onChange={(event) => update({ jobType: event.target.value })} className="mt-2 w-full rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] px-3 py-3 text-sm outline-none focus:border-[var(--brand)]">{["Full-time", "Internship", "Contract", "Part-time"].map((type) => <option key={type}>{type}</option>)}</select></label></div><div className="rounded-xl border border-amber-500/20 bg-amber-500/8 p-4 text-sm leading-6 text-amber-700 dark:text-amber-300"><div className="flex items-center gap-2 font-bold"><Icon name="user" className="h-4 w-4" />Human action is always required</div><p className="mt-1 text-xs opacity-90">JobBot will pause and ask you before it encounters a CAPTCHA, identity check, or application question that needs your response.</p></div><button type="button" onClick={saveSettings} className="inline-flex items-center gap-2 rounded-xl bg-[var(--brand)] px-4 py-3 text-sm font-bold text-slate-950 transition hover:brightness-110"><Icon name="check" className="h-4 w-4" />{saved ? "Settings saved" : "Save guardrails"}</button></div></section>
      <aside className="h-fit rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--card-shadow)]"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--brand)]">Queue status</p><div className="mt-4 flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${settings.enabled ? "bg-emerald-500/12 text-emerald-500" : "bg-[var(--surface-hover)] text-[var(--text-faint)]"}`}><Icon name="bolt" className="h-5 w-5" /></span><div><p className="font-bold">{settings.enabled ? "Ready to review" : "Paused"}</p><p className="text-xs text-[var(--text-muted)]">{settings.enabled ? `Up to ${settings.dailyLimit} roles per day` : "Turn on when you are ready"}</p></div></div><div className="mt-6 space-y-3 border-t border-[var(--border)] pt-5 text-sm"><div className="flex justify-between"><span className="text-[var(--text-muted)]">Minimum score</span><strong>{settings.minimumMatch}%</strong></div><div className="flex justify-between"><span className="text-[var(--text-muted)]">Applications today</span><strong>0 / {settings.dailyLimit}</strong></div><div className="flex justify-between"><span className="text-[var(--text-muted)]">Needs your action</span><strong className="text-emerald-500">0</strong></div></div></aside></div>
  </div></AppShell>;
}
